apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ghcr-secret.yaml

patches:
  - path: patch.json
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: argocd-server
  - path: patch.json
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: argocd-repo-server
  - path: patch.json
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: argocd-application-controller
  - path: patch.json
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: argocd-notifications-controller
  - path: patch.json
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: argocd-applicationset-controller
