apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-pagerduty
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: grafana-pagerduty
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: monitoring
        property: pagerduty-api-key
