apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-pagerduty
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    name: grafana-pagerduty
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: monitoring
        property: pagerduty-api-key
