apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: dex-config
    creationPolicy: Owner
  data:
  - secretKey: clientID
    remoteRef:
      key: dex-sso
      property: clientID
  - secretKey: clientSecret
    remoteRef:
      key: dex-sso
      property: clientSecret
