apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonAnnotations:
  argocd.argoproj.io/sync-wave: "100"

resources:
  - argo-workflows-sso.yaml
  - dex-config.yaml

patches:
  - path: argocd-cm.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-cm.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: argocd-dex-server.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
