apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pagerduty-key
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: pagerduty-key
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: monitoring
        metadataPolicy: None
        property: pagerduty-api-key
