apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - rbac.yaml
  # - sa.yaml

patches:
- target:
    version: v1
    kind: ServiceAccount
    name: argocd-repo-server
  path: sa.patch.json
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-repo-server
  path: deployment.patch.json
