apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgresql-user.yaml
  - postgresql-db.yaml

configMapGenerator:
  - name: dagster-dashboard
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dagster-pipeline.json=dashboards/dagster-pipeline.json
  - name: dagster-alerts
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
    files:
      - dagster-alerts.yaml=alerts/dagster-alerts.yaml
