apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgresql-user.yaml
  - postgresql-db.yaml
  - alerts/dagster-ksm-alerts.yaml

configMapGenerator:
  - name: dagster-health-dashboard
    files:
      - dagster-health-dashboard.json=dashboards/dagster-health-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
