apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: wildcard-cert-tls
  dnsNames:
    - "$(configmap:argocd/cluster-config#clusterDNSZoneName)"
    - "*.$(configmap:argocd/cluster-config#clusterDNSZoneName)"
  issuerRef:
    name: traefik
    kind: Issuer
