---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
type: Opaque
stringData:
  api-token: $(secret:argocd/traefik#CF_DNS_API_TOKEN)
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: traefik
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $(secret:argocd/traefik#CF_EMAIL)
    privateKeySecretRef:
      name: cloudflare-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-token
              key: api-token
